name: ⚙️ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] <title>"
labels: []
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A concise description of what the problem is.
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Implementation
      description: Not obligatory, but suggest ideas for how to implement the addition or change
